### ISSUE TITLE
Update the fetch events script to listen for the event emitted as a result of 'storeData'

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/dreamweaver#10]
Currently the use of viem's 'getLogs' is only listening to events emitted as a result of 'createPress'. This should be expanded to listen to events emitted as a result of a 'storeData' call.

**Comment by 0xTranqui** [comment]
also `overwriteData` and `removeData` call

**Comment by salieflewis** [comment]
Resolved in #11
