### ISSUE TITLE
repo structure could maybe be improved?

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/dreamweaver#13]
feels a bit confusing to have everything in a "server" folder.

are we good to remove the "onchain folder" and then just spill everything out into the root?

**Comment by salieflewis** [comment]
Onchain folder is now gone. Initially was also going to create a client folder. But if this is going to be moved into the larger Assembly Press repo, then maybe the client exists in a separate repo. And the server folder just becomes backend, or whatever this called, and that is it.

**Comment by salieflewis** [comment]
Can we close this?

cc: @jawndiego @0xTranqui
